CC=g++

primes1: primes1.cpp
	$(CC) -g -o primes1.out primes1.cpp

primes2: primes2.cpp
	$(CC) -g -o primes2.out primes2.cpp

switch1: switch1.cpp
	$(CC) -g -o switch1.out switch1.cpp

switch2: switch2.cpp
	$(CC) -g -o switch2.out switch2.cpp

clean:
	rm -rf *.out